version: '3.0'
services:
  product-app:
    container_name: product-app
    image: srinaga7084/productservice
    resatrt: on-failure
    ports:
      - 1066:9090
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
      - coupon-app    
  coupon-app:
    container_name: coupon-app
    image: srinaga7084/couponservice
    restart: on-failure
    ports:
      - 1055:9091
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      volumes:
        - ./sql:/docker-entrypoint-initdb.d
      ports:
        - 6666:3306
      healthcheck:
        test: "usr/bin/mysql --user=root --pasword=root --execute 'SHOW DATABASES'"
        internal: 4s
        timeout: 20s
        retries: 5